### ISSUE TITLE
Spammy structure generation; structures possibly ignore each other's spacing and separation settings

### ISSUE THREAD

**Issue by SplendidAlakey** [FinnSetchell/MoogsVanillaStructuresV2#3]
**MC** 1.19.2
**FAPI** 0.60.0
**MVS** 2.5.8

Hi! I'm having an odd issue with structures specifically from your mod. You have amazing default spacing and separation values, making structures rare and not spammy... after at least one of a kind has been generated. I'm not sure about the technicalities of the issue, so it's more of a speculation on my part, but it seems like structures only take structures of the same kind into consideration when calculating spacing/separation from other structures. 

For example, an abandoned library generates at coordinates X200 Z500, which means that now if another abandoned library was to spawn, it would have to be at least 400 chunks away. But if, say, a crystal wanted to spawn right next to the abandoned library, it totally could.

I've noticed this behavior only with structures from MVS, I'm using a couple of other mods that generate structures, but the worst I've came across was one of them generating directly in the middle of a random village. E.g. [The Graveyard](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-fabric) mod adds multiple types of graveyard structures and from my testing, none of them spawn close to each other (note: default values for them are way too low, I manually increased them via the config by at least x100). It didn't matter whether it was a single grave or a massive crypt, they simply didn't spawn next to each other. Another example is [Repurposed structures](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric), which adds many new versions of vanilla structures, like villages, ruined portals etc, all of which respect another structure's spacing.

Initially, I suspected some kind of mod interference, since default values for spacing and separation in MVS are very high, but I've gone ahead and tested 20 worlds with no other mods installed.

<details>
  <summary>Here are the results (click to expand) </summary>
  
1. Seed: `652540275449381318`, 2 big structures generated basically right at spawn. X: 10, Z: -3
![2022-08-31_23 35 53](https://user-images.githubusercontent.com/86702831/187792820-667cf18b-572c-4cad-a809-79a0357c9daa.png)

2. Seed: `5538876035694540081`, same thing. X: 7, Z: -5
![2022-09-01_00 01 10](https://user-images.githubusercontent.com/86702831/187793112-d0a0f28a-8e24-4e85-b3f4-b1583ec6902f.png)

3. Seed: `757783286943109150`, looks good, no structures for hundreds of blocks! X: -198, Z: -700
![2022-09-01_00 04 37](https://user-images.githubusercontent.com/86702831/187793707-c2155183-c816-4ac6-b398-d46ad628738e.png)

4. Seed: `7110449246181609552`, 5 structures generated next to each other, not counting the ruined portal, within the spawn area. X: 13, Z: 12
![2022-09-01_00 08 48](https://user-images.githubusercontent.com/86702831/187794090-ede4ba4e-6b27-4ce2-8be4-3982ba01dc3d.png)

5. Seed: `2504197529629243257`, _tumbleweed..._ Sorry, looks good :D X: 120, Z: -350
![2022-09-01_00 12 29](https://user-images.githubusercontent.com/86702831/187794628-a4c6d967-067d-4cca-a2e3-bde18e83174f.png)

6. Seed: `7666639132010226505`, 5 structures generated next to each other at spawn. X: -4, Z: 4
![2022-09-01_00 14 38](https://user-images.githubusercontent.com/86702831/187794781-68e687b2-dbeb-440e-9bea-d0847b5699f0.png)

7. Seed: `-2424297814624666443`, all good. X: -200, Z: 440
![2022-09-01_00 17 04](https://user-images.githubusercontent.com/86702831/187795043-7a9d4f6a-7e5a-4c57-b044-06194fcbf420.png)

8. Seed: `1785025892740334576`, 2 structures at spawn, too close to each other for my taste, but not the biggest deal; although this damn chicken is my personal nightmare, as it spawns very often and contains diamond blocks. X: -52, Z: 32
![2022-09-01_00 27 30](https://user-images.githubusercontent.com/86702831/187796467-874b8be2-8479-4a90-a598-bab1f56114ae.png)

9. Seed: `8801262436848432123`, all good, just some finicky generation. X: -46, Z: -78
![2022-09-01_00 30 24](https://user-images.githubusercontent.com/86702831/187796480-e104e59c-8dab-4942-8ecd-c37851173412.png)

10. Seed: `-4072558371689252310`, all good. X: -274, Z: 150
![2022-09-01_00 34 25](https://user-images.githubusercontent.com/86702831/187796812-1a4763be-3739-4b4f-83ab-cd2e6847af71.png)

11. Seed: `-4920469581643900081`, 3 structures practically next to each other. X: 197, Z: -1
![2022-09-01_00 38 53](https://user-images.githubusercontent.com/86702831/187797351-250e0363-616d-4c21-ba47-96831a7fd3cd.png)

12. Seed: `-6320972255716229774`, 6 structures next to each other, directly at spawn. X: -16, Z: 28
![2022-09-01_00 42 09](https://user-images.githubusercontent.com/86702831/187797690-836cbf88-86a8-4826-b287-d6b5b16234f0.png)

13. Seed: `-2752390096271778367`, 4 structures next to each other, at spawn. X: 138, Z: 0
![2022-09-01_00 44 30](https://user-images.githubusercontent.com/86702831/187797988-9bf5609a-9780-45e3-94c5-67d264d30096.png)

14. Seed: `-5213964339245291702`, 4 structures pretty close to each other, within the spawn area. X: 210, Z: 161
![2022-09-01_00 47 25](https://user-images.githubusercontent.com/86702831/187798300-2d8079ef-bff2-4b6c-a26e-80424974e14b.png)

15. Seed: `-8340261108942782912`, all good. X: 61, Z: 87
![2022-09-01_00 49 49](https://user-images.githubusercontent.com/86702831/187798529-e52b6873-b7aa-4f2e-92fb-978a90191027.png)

16. Seed: `-3982520022398894243`, all good. X: -2, Z: -97
![2022-09-01_00 51 55](https://user-images.githubusercontent.com/86702831/187798820-93f946a0-0d98-4ec6-a3a6-36654fe8ad25.png)

17. Seed: `-4557643995453436428`, all good. X: 476, Z: -149
![2022-09-01_00 55 24](https://user-images.githubusercontent.com/86702831/187799192-6d932715-af60-47c8-84ba-8efb61322f63.png)

18. Seed: `3906085188181581915`, all good. X: 340, Z: -107
![2022-09-01_00 58 33](https://user-images.githubusercontent.com/86702831/187799521-f37984bf-5950-4768-b61b-c96f4bdca449.png)

19. Seed: `6061000946855805090`, 5 structures very close to each other at spawn, not counting the village. X: 98, Z: 146
![2022-09-01_01 01 34](https://user-images.githubusercontent.com/86702831/187799855-d22504fc-6306-48df-a5f8-0b03f693ba68.png)

20. Seed: `-1491702770783723624`, 3 structures straight at spawn. X: 101, Z: 146
![2022-09-01_01 03 45](https://user-images.githubusercontent.com/86702831/187800065-a0f45a43-c386-4419-b76d-1876d73dfd11.png)

</details>

Additional observations:

1. Structures seem to get spammed more often if the world spawn is close to X: 0, Z: 0
2. If the spawn is not spammed with structures, that does not mean they won't get spammed elsewhere
3. Creating a new world does not warn you about any experimental world generation settings, however, after leaving and re-joining, it does
4. Birch forests, Dark oak forests, Spruce forests and Oak forests seem to be the most susceptible biomes to structure spam
5. Close proximity to water biomes, on the other hand, almost guarantees no spam; and deserts/mesas almost never have any structures at all
6. You either find no structures at all or multiple at once in a sort of cluster
7. That damn chicken seems to (occasionally?) ignore even it's own spacing/separation settings, as I've definitely came across 2 within less than 50 chunks from each other
8. Structures seem to become rare as intended after at least one of its kind was generated

Overall, out of 20 worlds that I've tested, 9 were good, no structures around that I could see, 11 had on average 4 structures directly at spawn. However, as I mentioned above, even though those 9 worlds had no clusters of structures at spawn, doesn't mean you won't find them if you explore enough.

**Comment by FinnSetchell** [comment]
First of all, thank you so much for the detailed issue report. These are definitely things I am, or will, look into for the next big release. 
1. I think I will add something to just stop all structures spawning within lets say ~25-30 chunks from spawn.
2. I will add something to stop any structure spawning within 10 chunks of another structure (this has lots of technical issues with which structures it can't spawn next to, as for example in a swamp or soul_sand_valley biome, there are fossil structures everywhere which would basically disable any of my structures spawning. Hopefully I will be able to filter which structures I choose not to spawn next to).
3. I have not come across this in my testing, I think I will add shut up experimental settings (https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings) to the recommended dependencies list as the message is just annoying. Alternatively, I might add it in natively, or make my own version of the mod. Basically, I want to get rid of that message entirely.
4. This is because those are the biomes where most structures can spawn. Hopefully point 2 will eliminate structure spam.
5. Again, this is because currently there aren't many structures that I want to spawn in those biomes. I will flag this as something we need to focus on, I think the entire team are prone to building more of the foresty, spruce type builds.
6. Yeah, I'd noticed this. For some reason the random generation tends to clump them together, no idea why, but ill have a look into it. Again, hopefully point 2 will at least limit it to one structure.
7. OK, not entirely sure why, at least in the 1.18.2 forge version, the min spacing is 600 chunks. I'll look into it, maybe 2.5.8 has different parameters, so ill check this later.
8. That's a really useful point, makes sense with how it's coded. I’ll look into it.

Thanks again for this really detailed issue, and sorry for the late reply, I've been setting up a modded community server so haven't been working on mvs for a few days.
I'm currently setting up data gen in all version which will make adding new structures way easier, so expect lots more, and with custom loot tables for the chests. Then I will go about stopping the structures from spawning too close to each other and too close to spawn. That will hopefully be enough for a new version with tonnes more structures. And then in the next version I will work on point 8 and hopefully just refine the rarity and other bits. I will also add a config to switch between 3 different rarities, common, sparse, and rare. with common being like what most other mods tend to be, sparse being how I like it (slightly less rare than current), and rare being you hardly ever see them.

Thanks,
FinnDog

p.s. I recommend joining the discord if I'm being slow replying in future, way easier to get hold of me and you can just point me here.

**Comment by SplendidAlakey** [comment]
1. That one alone would solve the biggest issue with this. Currently, it's highly likely that you will spawn next to a bunch of structures, some of which contain full gear, diamond blocks, etc.
2. Due to 1, I'd say this step isn't that important, as encountering structures next to each other far enough away from spawn is not problematic imo.
3. I am using BCLib, which disables it, in my actual modpack, so the message itself is not an issue. What is an issue is that the message appeared only after joining an already existing world, whereas it should warn you upon creating one as well.
4. and 5. Ah, thought about it, but decided not to speculate. Good to know.
6. My best guess is that they all have roughly the same spacing/separating settings, so when 10 structures are all seeking to spawn after 300 chunks, they do so all together. Maybe making each structure have a more unique value would help?
7. I didn't test the chicken structure nearly as extensively, but if I find a seed where the issue occurs, I'll let you know.

Unrelated to this issue, but since then I also found out that some houses that generate with armor stands inside have 2 armor stands in 1, not sure if it's intended? Looks like a bug since you get double the amount of items.

And no worries at all about the delayed response, the mod isn't unusable by any means. And it's been only a couple of days.

I'm thinking of getting a discord, because a lot of projects use it, but the problem is that I myself won't be nearly as responsive on it. Forums like github notify me about every message, and I can always go back to them at any time, whereas on discord if I missed something it's gone pretty much.

Thanks for looking into it!

**Comment by FinnSetchell** [comment]
Nice, I've started work on the next update. I'll tackle 1 first then, I've got an idea on how to prevent this. And maybe as a quick fix for 2, I'll make the spacings much more random. They are all different atm but most of the values are within 50-100 chunks of each other. Hard when there are so many structures that you want to have a similar rarity. I will also look into my original solution where I block spawns. I'll also look jnto the armour stands, my guess is that the original structure accidentally had two and it'll be as easy as braking one. 

no worries with discord either, I might look into a bot to help me watch github actually but idk.
Thanks

**Comment by FinnSetchell** [comment]
hey man, sorry it took a month, I've been busy irl. The new update is finally on its last few stages. Im going to be testing the 1.18.2 forge version and once im sure its doing everything we wanted ill update to all the other versions!
if you want me to send you an early release of the new mod for your testing then let me know, otherwise it should be on curseforge within a week : ) Thanks again for the feedback

**Comment by SplendidAlakey** [comment]
Yeah, no worries. I'm waiting for Create 1.19 to get ported to Fabric, to properly start playing, anyway. 1 week is fine, so I think I'll just wait for the release. Thanks for the update!
